### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by dakotahawkins**
Fixed everything VS complained about.

### CODE REVIEW

**Comment by mlangkabel** [comment]
Thanks for taking the time to fix these warnings. I think the warning about closing the socket twice was a real thing that actually happened sometimes!

We really appreciate your work on this project and we'd like to offer giving you collaborator access to this repository. 
This means that you would be able to create branches directly on this repository so you wouldn't have to sync your fork everytime something changes. However, we'd still ask you to issue pull requests for your changes because that provides the tools for talking about the changes before merging them.

**Comment by dakotahawkins** [comment]
@mlangkabel Sounds good to me. If it's OK with you I'd like to work out establishing some kind of "next" branch (that's what [git](https://github.com/git/git/branches) calls theirs, the name isn't important to me) where things like my include paths change could live after they're reviewed but before they're part of an official version.

**Comment by mlangkabel** [comment]
For the internal software development at @CoatiSoftware we use a different branching concept, but why not. We always like to try something new! I think [this article](http://nvie.com/posts/a-successful-git-branching-model/) has a good description of what you are proposing (but we'll only need the `master`, `next`, `release`, and some feature branches ;) )

**Comment by dakotahawkins** [comment]
We use the git flow branching strategy at work, and while it works very well we do have a massive codebase and need more than 1 long-lived release branch at a time.

I'm not sure this repo quite warrants all of _that_, but some easier way to get at the bleeding edge code might be good for interested users.

I really wish the extension gallery supported differentiating between stable and beta versions, so people could opt-in to those kinds of updates.

**Comment by mlangkabel** [comment]
Sure, lets keep it simple for this project. So we use the `next` branch for merging reviewed updates and features while the `master` branch has one merge-commit for each release. 

But I think that having short-lived release branches is a good idea, too. They should branch away from the `next` branch whenever we want to make a new release. These release branches should have commits for changing the version number and updating the changelog and get merged into `master` (for the actual release) and also back into `next` (to keep the changes to the version number and the changelog for the following releases).

**Pull request merged**
